elasticsearch:
  host: elasticsearch
  port: 9200
  username: elastic
  password: XeCx6ou5+x=_zWd1ZCXd2
  scheme: http

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

