server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

elasticsearch:
  host: localhost
  port: 9200
  username: elastic
  password: XeCx6ou5+x=_zWd1ZCXd2
  scheme: http

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: DEBUG